# {{=<% %>=}}
---
apiVersion: deployment.krateo.io/v1alpha1
kind: MicroservicePoc
metadata:
  name: <%#norm%>{{name}}<%/norm%>-microservice
spec:
  owner: simone
  title: <% name %>
  description: Microservice Deployment
  icon: "fa-solid fa-fire"
  tags:
    - microservice
    - template
    - krateo
    - poc
  links:
    - url: https://github.com/<% organizationName %>/<% repositoryName %>
      title: <% organizationName %>/<% repositoryName %>
      icon: "fa-brands fa-git"
  plugins:
    - name: resources
      value: <%#norm%>{{name}}<%/norm%>-microservice
      type: argocd
      icon: fa-solid fa-diagram-project
      endpointName: argocd
    - name: documentation
      values:
        - "[<% organizationName %>][<% owner %>-fire-<%#norm%>{{name}}<%/norm%>]README.md"
      type: doc
      icon: fa-solid fa-book
      endpointName: github
    - name: kubernetes
      value: deploymentId
      type: kubernetes
      icon: fa-brands fa-docker
    - name: pipelines
      values:
        - "[<% organizationName %>][<% owner %>-fire-<%#norm%>{{name}}<%/norm%>]Build Docker image for every commit"
      type: pipeline
      icon: fa-solid fa-person-running
      endpointName: github
  values:
    replicas: <% replicas %>
    organizationName: <% organizationName %>
    repositoryName: <% owner %>-fire-<%#norm%>{{name}}<%/norm%>
    destinationApiUrl: <% destinationEndpoint.target %>
    host: <% host %>
    description: Microservice PoC
    endpointName: <% destinationEndpoint.friendlyName %>
    namespace: krateo-system
    fromRepo:
      schema: https
      organizationName: krateoplatformops
      repositoryName: krateo-template-microservice
    toRepo:
      schema: https
      organizationName: <% organizationName %>
      repositoryName: <% owner %>-fire-<%#norm%>{{name}}<%/norm%>
      apiUrl: https://api.github.com
  # for editing purposes
  templateName: krateo-microservice
  flat:
    name: <% name %>
    replicas: <% replicas %>
    host: <% host %>
    organizationName: <% organizationName %>
    destinationEndpoint: <% destinationEndpoint.friendlyName %>
