apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: krateo-template-microservice
spec:
  package: "ghcr.io/krateoplatformops/krateo-template-microservice:latest"
  packagePullPolicy: Always
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
