apiVersion: krateo.io/v1alpha1
kind: Template
metadata:
  name: krateo-microservice
spec:
  owner: simone.ragonesi@kiratech.it
  title: Krateo Microservice
  description: Krateo Microservice Template
  icon: fa-solid fa-fire
  tags:
    - microservice
    - template
    - krateo
    - poc
    - demo
  widgets:
    - title: Test widget
      description: just a test (but mandatory!)
      properties:
        - title: Test
          key: test
          description: Unique name of the component
          required: true
          default: changeme
    - title: Name and description
      description: Name your app
      properties:
        - title: Name
          key: name
          description: Unique name of the component
          required: true
          default: firefire
    - title: Kubernetes
      properties:
        - title: Replicas
          key: replicas
          description: Number of replicas
          type: radio
          required: true
          default: "2"
          options:
            - title: "1"
              value: "1"
            - title: "2"
              value: "2"
            - title: "3"
              value: "3"
            - title: "4"
              value: "4"
            - title: "5"
              value: "5"
    - title: Expose application
      description: Expose your application
      properties:
        - title: Host
          key: host
          description: Hostname of the application
          required: true
          default: app.krateoplatformops.io
    - title: Git repository destination
      properties:
        - title: Organization Name
          key: organizationName
          description: Organization name
          required: true
          default: krateoplatformops
        - title: Endpoint
          key: destinationEndpoint
          description: github.com / gitlab.com / bitbucket.org
          required: true
          type: endpoint
